version: "3.8"

services:
  orbiens-mysql:
    image: mysql:8.4
    container_name: orbiens-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: orbiens
    networks:
      - orbiens-net
    volumes:
      - /opt/orbiens/mysql/data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -uroot -p$$MYSQL_ROOT_PASSWORD -e 'SELECT 1' >/dev/null 2>&1"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 60s
  orbiens:
    image: lxien/orbiens:0.10.0
    container_name: orbiens
    restart: unless-stopped
    ports:
      - "8080:8080" # HTTP 隧道代理服务
      - "8020:8020" # 管理面板
      - "9527:9527" # 控制隧道
      - "9050-9099:9050-9099" # TCP 隧道代理服务
    environment:
      JAVA_OPTS: "-Xms256m -Xmx256m -XX:MaxDirectMemorySize=512m -XX:+UseG1GC --enable-native-access=ALL-UNNAMED"
      MYSQL_PASSWORD: 123456
      MYSQL_HOST: orbiens-mysql
      TZ: Asia/Shanghai
    volumes:
      - /opt/orbiens/logs:/app/logs
    networks:
      - orbiens-net
    depends_on:
      orbiens-mysql:
        condition: service_healthy
networks:
  orbiens-net:
    driver: bridge