server_addr = "localhost"
server_port = 9527

[auth]
token = "414083A8563774142CAC91DDB5C9A2ED"

##############################################################################################################
[connection]
[connection.retry]
initial_delay = 2
max_delay = 8
max_retries = 5

[connection.pool]
enabled = true

[connection.pool.multiplex]
plain = true
encrypt = true

[connection.pool.direct]
plain_count = 1
encrypt_count = 2

[transport]
[transport.multiplex]
enabled = true

[transport.tls]
enabled = true
cert_file = "/Users/lxien/Desktop/workspace/orbien/cert/transport/client.crt"
key_file = "/Users/lxien/Desktop/workspace/orbien/cert/transport/client.key"
ca_file = "/Users/lxien/Desktop/workspace/orbien/cert/transport/ca.crt"

[[proxies]]
name = "web1"
protocol = "https"
custom_domains = ["a.domain1.com", "b.domain1.com"]
targets = [
    { port = 8084 },
    { host = "127.0.0.1", port = 8088, weight = 10, name = "web-instance-1" },
    { host = "127.0.0.1", port = 8084, weight = 1, name = "web-instance-1" }
]
force_https = true
#[proxies.ssl]
#cert_file = "cert/domains/lxien.com/fullchain.pem"
#key_file = "cert/domains/lxien.com/privkey.pem"

[proxies.health_check]
enabled = true
type = "http"
interval = 4
timeout = 5
max_failed = 3
path = "/health"
[[proxies]]
name = "web1-http"
protocol = "http"
custom_domains = ["d.domain1.com", "ba.domain1.com"]
targets = [
    { host = "127.0.0.1", port = 8084, weight = 10, name = "web-instance-1" }
]

[[proxies]]
name = "tcp2"
protocol = "tcp"
local_ip = "127.0.0.1"
local_port = 8089
[proxies.transport]
multiplex = true
[proxies.health_check]
enabled = true
type = "tcp"
interval = 8
timeout = 5
max_failed = 3

[[proxies]]
name = "udp1"
protocol = "udp"
local_ip = "127.0.0.1"
local_port = 9999
remote_port = 9060
[proxies.transport]
multiplex = true

[log]
level = "debug"
path = "/Users/lxien/Desktop/workspace/orbien/logs"
name = "orbienc.log"
archive_pattern = "orbienc.%d{yyyy-MM-dd}.log"
log_pattern = "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
max_history = 1
total_size_cap = "1MB"
