server_addr = "0.0.0.0"
server_port = 9527
http_proxy_port = 80
https_proxy_port = 8443
base_domain = "domain1.com"

[transport]
# TLS
[transport.tls]
enabled = true
cert_file = "/Users/xiaoniucode/Desktop/workspace/etp/cert/transport/server.crt"
key_file = "/Users/xiaoniucode/Desktop/workspace/etp/cert/transport/server.key"
#ca_file = "/Users/xiaoniucode/Desktop/workspace/etp/cert/transport/ca.crt"
#key_pass=""

[auth]
[[auth.tokens]]
name = "macos"
token = "414083A8563774142CAC91DDB5C9A2ED"

#管理界面
[dashboard]
enabled = true
addr = "localhost"
port = 8030
username = "admin"
password = "123456"

#公网端口分配范围
[port_policy]
start = 9050
end = 9099
